#!/bin/bash

git diff --cached

while read st file
do
    # 文件末为不是 .php 时输出文件，并跳出本次循环
    if [[ ! "$file"  =~ (\.php$) ]]
    then
        echo $file
        continue
    fi

    PHP_LINT=`php -l $file`
    # 语义检查
    if [ 0 -ne $? ]
    then
        echo "\033[31m 语法错误：$PHP_LINT \033[0m"
        exit 1
    fi

    # exit检查
    PHP_EXIT=$(grep -rni 'exit()' $file)
    if [[ $PHP_EXIT ]]
    then
	echo -e "\033[31m 存在断点exit：$PHP_EXIT \033[0m"
        exit 1
    fi

    # die检查
    PHP_DIE=`grep -rni 'die()' $file`

    if [[ $PHP_DIE ]]
    then
        echo -e "\033[31m 存在断点die：$PHP_DIE \033[0m"
        exit 1
    fi


done <<EOF
`git diff --cached --name-status`
EOF

exit 0
